export const CRYPTO_DATA_REQUEST = "CRYPTO_DATA_REQUEST";
export const CRYPTO_DATA_SUCCESS = "CRYPTO_DATA_SUCCESS";
export const CRYPTO_DATA_FAILURE = "CRYPTO_DATA_FAILURE";
export const TRANSACTION_DATA_REQUEST = "TRANSACTION_DATA_REQUEST";
export const TRANSACTION_DATA_SUCCESS = "TRANSACTION_DATA_SUCCESS";
export const TRANSACTION_DATA_FAILURE = "TRANSACTION_DATA_FAILURE";
export const CRYPTO_RESET_DATA = "CRYPTO_RESET_DATA";
